CREATE DATABASE DMART;

USE DMART;

/* || 1) TOTAL REVENUE || */
  
SELECT FORMAT(SUM(`Sales`), "#.##") AS TOTAL_REVENUE
FROM `dmart data`;

/* || 2) TOTAL PROFIT || */
  
SELECT FORMAT(SUM(`Profit`), "#.##") AS TOTAL_PROFIT
FROM `dmart data`;

/* || 3) TOTAL DISCOUNT || */
  
SELECT FORMAT(SUM(`Discount`), "#.##") AS TOTAL_DISCOUNT
FROM `dmart data`;

/* || 4) AVERAGE ORDER VALUE || */
  
SELECT ROUND(SUM(`Sales`) / COUNT( DISTINCT `﻿Order ID`),2) AS AVERAGE_ORDER_VALUE
FROM `dmart data`;

/* || 5) PROFIT MARGIN || */
  
SELECT CONCAT(ROUND((SUM(`Profit`) / SUM(`Sales`) * 100),2), " %") AS PROFIT_MARGIN
FROM `dmart data`;

/* || 6) SALES AND PROFIT BY REGION || */ 
  
SELECT `Region` AS REGION, FORMAT(SUM(`Sales`), "#.##") AS TOTAL_SALES,
FORMAT(SUM(`Profit`), "#.##") AS TOTAL_PROFIT
FROM `dmart data`
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;

/* || 7) SALES AND PROFIT BY CATEGORY || */
  
SELECT `Category` AS CATEGORY, FORMAT(SUM(`Sales`), "#.##") AS TOTAL_SALES,
FORMAT(SUM(`Profit`), "#.##") AS TOTAL_PROFIT
FROM `dmart data`
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC;

/* || 8) SALES, PROFIT AND DISCOUNT BY SUB CATEGORY || */
  
SELECT `Sub Category` AS SUB_CATEGORY, FORMAT(SUM(`Sales`), "#.##") AS TOTAL_SALES,
FORMAT(SUM(`Profit`), "#.##") AS TOTAL_PROFIT, FORMAT(SUM(`Discount`), "#.##") AS TOTAL_DISCOUNT
FROM `dmart data`
GROUP BY SUB_CATEGORY
ORDER BY TOTAL_SALES DESC;

/* || 9) PROFIT AND PROFIT MARGIN BY CATEGORY AND REGION || */
  
SELECT `Category` AS CATEGORY, `Region` AS REGION, FORMAT(SUM(`Profit`), "#.##") AS TOTAL_PROFIT,
CONCAT(ROUND(SUM(`Profit`)/SUM(`Sales`) * 100, 2), " %") AS PROFIT_MARGIN
FROM `dmart data`
GROUP BY CATEGORY, REGION
ORDER BY TOTAL_PROFIT DESC;

/* || 10) TOP 5 CITIES BY PROFIT MARGIN || */
  
SELECT `City` AS CITY, CONCAT(ROUND(SUM(`Profit`)/SUM(`Sales`) * 100, 2), " %") AS PROFIT_MARGIN
FROM `dmart data`
GROUP BY CITY
ORDER BY PROFIT_MARGIN DESC
LIMIT 5;

/* || 11) TOP 5 CITIES BY SALES AND PROFIT || */
  
SELECT `City` AS CITY, FORMAT(SUM(`Sales`), "#.##") AS TOTAL_SALES,
FORMAT(SUM(`Profit`), "#.##") AS TOTAL_PROFIT
FROM `dmart data`
GROUP BY CITY
ORDER BY TOTAL_SALES DESC
LIMIT 5;

/* || 12) TOP 10 CUSTOMERS BY SALES, PROFIT, PROFIT MARGIN || */

SELECT `Customer Name` AS CUSTOMER, FORMAT(SUM(Sales), "#.##") AS SALES,
FORMAT(SUM(Profit), "#.##") AS PROFIT, CONCAT(ROUND(SUM(Profit)/SUM(Sales) * 100, 2), " %") AS PROFIT_MARGIN
FROM `dmart data`
GROUP BY CUSTOMER
ORDER BY SALES
LIMIT 10;

/* || 13) WAQTD CATEGORY, REGION, SALES, PROFIT AND DISCOUNT FROM DMART DATA WHERE CATEGORY IS FOOD GRAINS AND SNACKS OR
           REGION IS SOUTH AND WEST || */
           
SELECT CATEGORY, REGION, FORMAT(SUM(SALES), "#.##") AS SALES,
FORMAT(SUM(PROFIT), "#.##") AS PROFIT, ROUND(SUM(DISCOUNT),2) AS DISCOUNT
FROM `dmart data`
WHERE CATEGORY IN("FOOD GRAINS","SNACKS") AND REGION IN("SOUTH","WEST")
GROUP BY CATEGORY, REGION
ORDER BY SALES DESC;

